### ISSUE TITLE
在线解码部分码库解码问题

### ISSUE THREAD

**Issue by lazyling** [irext/core#1]
1.使用index id为3462码库进行解码时，会报错停止，需要重启进程。
2.使用index id为13021码库进行解码时，返回cause是success，但entity为null
3.连续调用多个码库进行解码时，容易报错停止，需要重启进程。

**Comment by strawmanbobi** [comment]
2.使用index id为13021码库进行解码时，返回cause是success，但entity为null
// release 码库哈希值错误，已经解决。

**Comment by lazyling** [comment]
4.get_ac_parameters的API，remoteIndexId=128时返回结果为空，remoteIndexId=其他时报错停止。

![11551887433_ pic_hd](https://user-images.githubusercontent.com/1519438/53895101-416fc380-406c-11e9-8956-a796035e2900.jpg)

**Comment by strawmanbobi** [comment]
请问 get_ac_parameters 导致 crash 的是 index ID 是多少？
