### ISSUE TITLE
试了下，没效果

### ISSUE THREAD

**Issue by Liweiwei2Anna** [irext/core#11]
请问这个数据的覆盖率怎么样？ 家里的电视和空调都没啥效果？

**Comment by strawmanbobi** [comment]
您好。
请问下你测试的过程是怎样？
这个码库大概是 2017 年左右的，不过据最近的用户反馈看，覆盖率还是比较高的。所以不清楚是不是你测试过程是怎样？还望告知。thanks~

**Comment by Liweiwei2Anna** [comment]
我的手机华为P20 华为阉割了红外模块，我买了个外接红外，测试了下没效果，不过我用应用市场的遥控精灵测试了下，还是有效果的，证明外接红外OK。不过是基于我自己搭建的服务，你们的因为前两天服务器宕机了，没能正常测试，晚上我回家再试试， 谢谢

**Comment by strawmanbobi** [comment]
我知道了。遥控精灵是针对那个耳机口的发射器做过定制的，换句话说那个耳机口的外接设备只有遥控精灵支持。以前有个小伙伴自己研究过怎样用 iOS 的耳机口发射，这个要自己写代码实现的。我的 demo 没做这个硬件的支持的。
BTW：耳机口的原理好像是说用音频调制的方式调制 38KHz 红外载波，不过我也没试过。
服务你自己搭也可以的。手机的话还是建议买个红米手机带红外的来试。我用的红米就能控制。

**Comment by Liweiwei2Anna** [comment]
嗯，是的，我晚上试了，不可以，应该是耳机口外接设备的原因。谢谢啦，我买个红米试试！

**Comment by strawmanbobi** [comment]
不用客气，有问题请随时提。
