### ISSUE TITLE
20200406版数据库问题

### ISSUE THREAD

**Issue by JustQY** [irext/core#14]
![image](https://user-images.githubusercontent.com/9473678/80302606-907f3780-87dd-11ea-92f0-9ff910e650c3.png)
如图是新版数据的remote_index表数据
我才用离线方式，这个和上一版本差别太大了，并且需要额外很多操作才能找到对应的离线文件。
上一版我只需要再remote_map字段结果前统一加上“irda_”就能找到了，这次这么修改的原因是为何呀，很难提取出和离线文件相关的参数了。
另外如果我如果依然用上一版数据库会有问题吗？我只是用来查基础索引数据从而找到对应的离线bin文件

**Comment by strawmanbobi** [comment]
你好，上一版是没问题的。这一版我看看。估计是转换工具的问题。这一版用了个在线免费的转换工具，搞不好是它给我弄进去的垃圾数据。

**Comment by strawmanbobi** [comment]
修改好了，请从 http://irext-lib-release.oss-cn-hangzhou.aliyuncs.com/0.2.5/pack/database.tar.gz 下载更新。谢谢。
给您带来不便，请谅解。
