### ISSUE TITLE
Offline decoding failed when using some ac .bin files

### ISSUE THREAD

**Issue by Huangyidao2006** [irext/core#16]
failed files are listed as following:
irda_new_ac_5802.bin,irda_new_ac_6062.bin,irda_new_ac_6757.bin,irda_new_ac_11737.bin,irda_new_ac_5597.bin,irda_new_ac_6057.bin,irda_new_ac_4712.bin,irda_new_ac_4297.bin,irda_new_ac_6727.bin,irda_new_ac_5392.bin,irda_new_ac_1257.bin,irda_new_ac_10547.bin,irda_new_ac_6047.bin,irda_new_ac_6752.bin,irda_new_ac_4187.bin,irda_new_ac_6647.bin,irda_new_ac_20000.bin,irda_new_ac_1252.bin,irda_new_ac_2609.bin,irda_new_ac_3727.bin,irda_new_ac_2407.bin,irda_new_ac_5402.bin,irda_new_ac_577.bin,irda_new_ac_5437.bin,irda_new_ac_6652.bin,irda_new_ac_5382.bin,irda_new_ac_5702.bin,irda_new_ac_6662.bin

**Comment by strawmanbobi** [comment]
我先看下是不是对应那些本来就验证不通过的。如果除了那些之外我再做下标记。多谢。

**Comment by strawmanbobi** [comment]
均已 Mark，看来空调的码库质量和扩充是个刻不容缓的问题。头大啊。
多谢小哥帮忙测试，这周把你加入特别致谢榜单。
