### ISSUE TITLE
能否添加空调显示的功能

### ISSUE THREAD

**Issue by killer-p** [irext/core#17]
感谢开源！
我使用的是格力空调的码库，控制码为2582的文件。能正常使用，就是空调不会显示，也就是灯光没打开。
希望能增加这个功能。我看到代码中t_remote_ac_status结构体有ac_display，ac_sleep和ac_timer变量，在代码中似乎没有对这三个变量进行操作，可能是还未完善吗？以后会改进这个功能吗

**Comment by killer-p** [comment]
不好意思，原来是2582的码库不支持灯光，其他的码库是有自带灯光的！打扰

**Comment by strawmanbobi** [comment]
好的。但是实事求是的说 IRext 的空调码里是没有灯光显示功能的。要依靠一方去解决这个问题并不容易（因为牵涉到众多码库的录入问题）。
目前 IRext 有个附属项目，叫 IRIS，从官网主页可以看到入口，它旨在通过一个开放的框架，让码库的使用者可以便捷的根据自己的需要录入码库（当然我自己也在持续录入），只不过 IRIS 今年计划是不支持空调的，我自己录入的也都是非空调类型。
今年 IRIS 的整体框架会计划完成开发（目前进度大概在 60% 左右），然后明年计划是重点攻一攻空调编码这个业界难题。
跟踪进展可以关注 IRext 定期的 release note。
由于是个人在 996 工作状态下，还要业余承担整个 IRext+IRIS 的开发，工作量相当巨大，因此进展比较慢。但是我会持续推进。还多谢支持。
