### ISSUE TITLE
decode api 不能获取红外载波频率

### ISSUE THREAD

**Issue by FounderSG** [irext/core#2]
头文件里没有看到怎么获取载波频率，encode的python代码里可以看到原始protocol xml文件里有frequency，但没有pack进protocol binary。这是一个设计上的缺陷吗？

**Comment by strawmanbobi** [comment]
您好，目前所有的码库都是 38K 的码。

**Comment by FounderSG** [comment]
建议增加载波频率的信息，可能空调的遥控器都用38K，其它的设备用非38K还是挺多的。

**Comment by strawmanbobi** [comment]
建议不错，采纳，下一版增加一个字段。
