### ISSUE TITLE
在调用空调ir_decode的时候出现crash

### ISSUE THREAD

**Issue by FatDogJOE** [irext/core#3]
用swift调用ir_decode的时候，在ac_status结构体里面的ac_temp传入了16，导致程序崩溃

**Comment by strawmanbobi** [comment]
请列举出具体的 remote_map，以及解码接口传入的 ac_status 参数。谢谢。

**Comment by strawmanbobi** [comment]
请**按照最新文档**，试一下 0.2.1 版本，谢谢。
