### ISSUE TITLE
function_id问题

### ISSUE THREAD

**Issue by yuanchaowang** [irext/core#4]
感谢提供的irext红外库，在学习源码的时候，有以下问题
1、在ir_ac_parse_parameter.c里面的函数parse_function_1里面，可以看到function_id对应的数据是存放在数组function1->comp_data偏移为function_id的位置。但是在最终使用的时候，又是从funtion - 1里面去取数据，两边匹配不上

2、想明白 风向枚举定义：SWING_TYPE_NORMAL SWING_TYPE_SWING_ONLY SWING_TYPE_NOT_SPECIFIED的区别

**Comment by strawmanbobi** [comment]
您好。第一个问题容我稍微 review 下代码，写得太久了，忘记了。
第二个问题：SWING_TYPE_NORMAL 就是支持扫风和定向风两种模式；SWING_TYPE_SWING_ONLY 就是只支持扫风，不支持定向风。SWING_TYPE_NOT_SPECIFIED 是指码库里没指明支持什么。所以不能操纵风向或者扫风。

**Comment by strawmanbobi** [comment]
第二个问题，请注意下在 parse_function_1 函数分析完 seg_len 之后，有一处处理：
UINT8 function_id = (UINT8) (data[*trav_offset] - 1);
这里 data[*trav_offset] 是真正的 function_code，从 1 开始，表示 POWER，但是后面为了作为mode_seg的下标，做了个 -1 操作，从 0 开始。
在使用的时候，具体来说是 apply_function 函数当中，同样把传入的 function - 1 作为 function_1.comp_data 的下标来处理。按键码对应 function 的转换这个是最新 0.2.1 版本里新增的（之前是直接传入按键码，这样对于有 UI 的客户应用不够友好，所以改了），转换位置在 ir_ac_control 的入口处。

如果你需要的话，我可以把最初设计空调编码的文档私信发给你。不要公开。

**Comment by yuanchaowang** [comment]
1、我是看美的的new_ac_11272这个文件里面的tag:function_1，解析出来格式
09 0602D60329040705F8
0D 0800AD015202AF0350044505BA
0D 2200AD015202AF035004A5055A
0D 2900AD015202AF035004C5053A
如果不减1，这样看起来有function_id就是06 08 22 29，目前最大function才7（AC_FUNCTION_WIND_FIX），那8这个function_id也没有意义了。因为这款空调正好扫风是一个固定编码，所以我才以为应该有7这个fid。
2、顺便问下AC_FUNCTION_WIND_SWING和AC_FUNCTION_WIND_FIX需要在什么时候传入呢
3、空调设计文档，如果可以摘抄部分给我可以吗

**Comment by strawmanbobi** [comment]
第一个问题：我今晚加了个打印调试了下，对于 irda_new_ac_11272.bin，parse 出来的 function_id 有：
5，7，33，40。说明它支持这四个功能。但是 33 和 40 我算法不支持。所以有效功能是 5：wind_speed，7：wind mode fix。你可以自己架设一个 cmake 环境，把 decode core 编译成可执行程序，输入码库 bin 文件，就可以调试了。

第二个问题：所有的 FUNCTION 参数，目前都不需要你在调用解码接口的时候传入，你只要按照按键引射表传入按键code（key_code）就可以了。算法内部会根据 key_code 转换成 function_id。

**Comment by yuanchaowang** [comment]
![f1](https://user-images.githubusercontent.com/7270975/60146651-f0dbcc00-97fc-11e9-9973-62d2134becb7.png)
从图上可以看到，文件里面记录的值是8 ，减一就是7，也就是AC_FUNCTION_WIND_FIX的值，但是你下面直接存放在偏移为7的地方。
![飞](https://user-images.githubusercontent.com/7270975/60146749-5334cc80-97fd-11e9-8ce8-6d76490209a5.png)
但是看apply_function的地方，又去从function_id - 1的地方去取，那么如果我传入AC_FUNCTION_WIND_FIX,那肯定导致无效了
