### ISSUE TITLE
空调解析关于风向信息bug

### ISSUE THREAD

**Issue by yuanchaowang** [irext/core#5]
从parse_swing_info可以看到风向个数是长度+1再除以2（si->mode_count = (UINT8) ((tag->len + 1) >> 1); ）
正常情况没有问题，但是如果风向个数为两位数就有问题了，刚好在irda_new_ac_11092的风向有十多个，对应tag如下（TAG_AC_SWING_INFO=0,1,2,3,4,5,6,7,8,9,10,11,12）。
我这边改成数逗号个数来解决这个问题

**Comment by strawmanbobi** [comment]
好的，我近期来看下。扩展下字段长度。谢谢指出。

**Comment by strawmanbobi** [comment]
已经修改到 0.2.2
