### ISSUE TITLE
ir_ac_control增加按键映射后, 与CLI原有按键映射有冲突

### ISSUE THREAD

**Issue by yungpin** [irext/core#7]
目前代码有两条路径调用解码函数:
1. JNI路径: ir_ac_control -> ir_decode -> ir_decode_combo -> Java_net_.....
2. CLI路径: ir_ac_control -> ir_decode -> decode_as_ac -> main

代码在 ir_ac_control  函数中增加了按键映射后, JNI路径应该没问题了, 但是CLi路径有些异常, 在decode_as_ac 函数中, 把"WASDQ12"等键盘按键转换成function_code, 类型是枚举(范围1-8), 然后传入ir_decode, 再传入ir_ac_control , 但是ir_ac_control 增加了一次映射后, 原本是想把JNI传入的0-13按键码转成function_code, 但CLI调用路径中传入的已经是function_code, 导致重复转码.

**Comment by strawmanbobi** [comment]
1. ri_decode_combo 只是为了方便把 open, parse, decode, close 这 4 个动作连接在一起执行，本质还是调用的 ir_decode 接口。这个接口也是 C library 对应用程序的唯一解码接口。
2. ir_decode 在走了 AC 分支之后直接调用 ir_ac_control，在 ir_ac_control 当中有对应用程序根据文档按键映射输入的 key_code，针对 AC function_code 的一次转换，在 AC 的控制当中，只有 function_code 是有意义的，key_code 只是逻辑上对用户应用程序的映射。
3. CLI 已经年久失修了，这里确实是一个 bug，我后续会修复 CLI 当中的错误调用。

所以目前针对你提的问题，建议是：
1. 如果坚持要用 CLI 模式对你的产品进行验证，请自己调用 decode library，写一个可执行程序，直接调用 decode library。
2. 也可以试用在线解码 API 或者 jni example 当中的 Java 范例进行调用。因为这二者都是直接调用的 decode library，不存在中间映射关系，当然，按键映射需要参考文档，在应用当中做适当输入。
3. CLI 的问题我会在下一版解决。
