### ISSUE TITLE
different parameter decode to same result

### ISSUE THREAD

**Issue by FounderSG** [irext/core#8]
new_ac_10018
function code = AC_FUNCTION_POWER
ac_status = power on; cool mode; temp 18; wind_dir 0;
no matter what wind_speed is, the decode result is identical.

It seemed that apply_function will overwrite bits set by apply_wind_speed.

is this expected behaviour? or new_ac_10018 protocol definition is incorrect?

**Comment by strawmanbobi** [comment]
这个我要动手实践一下才能告诉你答案。上班时间不方便，今晚或者周末吧。
