### ISSUE TITLE
如何实现decode的逆过程

### ISSUE THREAD

**Issue by FounderSG** [irext/core#9]
空调接收到遥控器的红外信号后要怎么做才可以还原出ac_status呢？
如果模式，温度，风向，风速分别对应一些数据位，那么还原的过程就很容易，irext的协议并不是这样，每个参数对应的数据位可能会被后面的参数覆盖。
有没有一个优雅的办法实现decode的逆过程？

**Comment by strawmanbobi** [comment]
这个问题涉及到 AC code 的编码，而不是解码。
你的问题大致拆解成几个阶段：
1. 空调码逆向 ： 需要数字红外分析仪配合，并且需要人工干预进行逆向，判断每个 status 域影响的 default code bit 范围。
2. 按照解码算法 apply 的先后顺序推断每个影响 default code 的域应该设计的模式和参数，编码到原始 XML 文件里（IRext 的原始码库都是用 XML 描述的，包括空调和电视机等）
3. 利用 core/src/encoder 进行二进制编码。

空调编码需要你事先读懂 编、解码算法以及需要一份攻略。如果有兴趣可以加我微信或者钉钉，ID都是 strawmanbobi。攻略不公开。

**Comment by strawmanbobi** [comment]
另外，在认知上要明确一点：空调不同属性在 bit 区间的覆盖是合理现象。并不是说每个属性所覆盖的 bit 区间都是不相交的。所以空调的逆向非常困难。

**Comment by Caffreyfans** [comment]
状态码逆向简直让人崩溃，我没用 irext 之前我尝试逆向我们寝室空调的状态码。就只逆向一个型号的都特别困难。模式，温度，风向这些状态确实在红外协议里对应固定的数据位，但是难就难在如果找出这些数据位以及这些数据位上对应的数据对应的哪种状态。要知道这个协议里还有校验位以及时间位，有这两个鬼东西在会在逆向的时候增添许多麻烦，我试了一个月之后就勉强找到了一个温度的数据位，然后就放弃了太难了。我真不知道那些万能红外是怎样获得那些不同电器的红外协议的，它们该不会是直接从厂家拿的吧？

> 空调接收到遥控器的红外信号后要怎么做才可以还原出ac_status呢？
> 如果模式，温度，风向，风速分别对应一些数据位，那么还原的过程就很容易，irext的协议并不是这样，每个参数对应的数据位可能会被后面的参数覆盖。
> 有没有一个优雅的办法实现decode的逆过程？

**Comment by strawmanbobi** [comment]
需要有一些耐心 : )
我如果后面有空，也会尝试用算法的方式做一些逆向。
